apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: prometheus-reloader
build:
  artifacts:
    - image: laggyluke/prometheus-reloader
deploy:
  kubectl:
    manifests:
    - k8s/*.yaml
portForward:
  - resourceType: pod
    resourceName: prometheus
    port: 9090
